const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];let state={},tab='portfolio',rows=[],cols=[],sort={key:'',desc:false},timer;
async function api(url,opt){let r=await fetch(url,opt);if(!r.ok)throw Error(await r.text());return r.json()}function showError(e){let x=$('#error');x.hidden=false;x.innerHTML=`${e.message} <button onclick="refresh()">↻</button>`}async function i18n(lang){let t=await api('/i18n/'+lang+'.json');$$('[data-i18n]').forEach(x=>x.textContent=t[x.dataset.i18n]||x.dataset.i18n);$$('[data-placeholder]').forEach(x=>x.placeholder=t[x.dataset.placeholder]||'')}
const flat=(o,p='',r={})=>{for(let[k,v]of Object.entries(o||{})){let n=p?p+'.'+k:k;if(v&&typeof v==='object'&&!Array.isArray(v))flat(v,n,r);else r[n]=Array.isArray(v)?JSON.stringify(v):v??'н/д'}return r};
function portfolio(){let a=[];(state.snapshot?.accounts||[]).forEach(ac=>ac.positions.forEach(p=>a.push(flat({...p,account_id:ac.id,account_name:ac.name})))) ;return a}function operations(){return(state.snapshot?.operations||[]).map(flat)}
function render(){let q=$('#search').value.toLowerCase();let view=rows.filter(r=>Object.values(r).some(v=>String(v).toLowerCase().includes(q)));if(sort.key)view.sort((a,b)=>String(a[sort.key]??'').localeCompare(String(b[sort.key]??''),undefined,{numeric:true})*(sort.desc?-1:1));cols=[...new Set(view.flatMap(Object.keys))];let g=$('#group').value;if(g)view.sort((a,b)=>String(a[g]??'').localeCompare(String(b[g]??'')));$('thead').innerHTML='<tr>'+cols.map(c=>`<th data-c="${c}">${c}${sort.key===c?(sort.desc?' ▼':' ▲'):''}</th>`).join('')+'</tr>';let html='',last=Symbol();for(let r of view){if(g&&r[g]!==last){last=r[g];html+=`<tr class="group"><td colspan="${cols.length}">▾ ${g}: ${last}</td></tr>`}html+='<tr>'+cols.map(c=>`<td>${highlight(String(r[c]??'н/д'),q)}</td>`).join('')+'</tr>'}$('tbody').innerHTML=html;$$('th').forEach(h=>h.onclick=()=>{sort.desc=sort.key===h.dataset.c?!sort.desc:false;sort.key=h.dataset.c;render()});$$('tbody tr:not(.group)').forEach((tr,i)=>tr.ondblclick=()=>{$('#details pre').textContent=JSON.stringify(view[i],null,2);$('#details').showModal()});$('#group').innerHTML='<option value="">Группировка</option>'+cols.map(c=>`<option ${c===g?'selected':''}>${c}</option>`).join('')}
function highlight(s,q){let e=s.replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));if(!q)return e;return e.replace(new RegExp(q.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'ig'),'<mark>$&</mark>')}
async function refresh(){try{$('#error').hidden=true;if(tab==='instruments'){let p=new URLSearchParams();['type','currency','exchange','sector','risk','frequency','coupon_type','rate_from','rate_to','month'].forEach(k=>{if($('#'+k).value)p.set(k,$('#'+k).value)});p.set('q',$('#search').value);let x=await api('/api/catalog?'+p);rows=x.instruments.map(flat);$('#updated').textContent=new Date(x.updated_at).toLocaleString();render();return}let x=await api('/api/refresh',{method:'POST',body:JSON.stringify({from:$('#from').value,to:$('#to').value})});state.snapshot=x;rows=tab==='portfolio'?portfolio():operations();render()}catch(e){showError(e)}}
async function selectTab(t){tab=t;$('#settings').hidden=t!=='settings';$('#grid').hidden=t==='settings';$('#toolbar').hidden=t==='settings';$('#filters').hidden=t!=='instruments';if(t==='portfolio'){rows=portfolio();render()}else if(t==='operations'){rows=operations();render()}else if(t==='instruments')await refresh()}
async function init(){try{state=await api('/api/state');await i18n(state.settings.language||'ru');let f=$('#settings form');for(let[k,v]of Object.entries(state.settings))if(f.elements[k])f.elements[k].value=v;selectTab('portfolio');schedule()}catch(e){showError(e)}}function schedule(){clearInterval(timer);let n=+state.settings.auto_refresh_minutes;if(n>0)timer=setInterval(refresh,n*60000)}
$$('[data-tab]').forEach(b=>b.onclick=()=>selectTab(b.dataset.tab));$('#refresh').onclick=refresh;$('#search').oninput=()=>tab==='instruments'?refresh():render();$('#group').onchange=render;$$('#filters input,#filters select').forEach(x=>x.onchange=refresh);$('#force').onclick=async()=>{await api('/api/catalog?force=1');refresh()};$('#export').onclick=async()=>{let data=[cols,...$$('tbody tr:not(.group)').map(tr=>[...tr.cells].map(c=>c.textContent))];alert((await api('/api/export-view',{method:'POST',body:JSON.stringify(data)})).path)};$('#settings form').onsubmit=async e=>{e.preventDefault();let o={...state.settings};new FormData(e.target).forEach((v,k)=>o[k]=['retries','retry_delay_ms','auto_refresh_minutes','catalog_ttl_hours'].includes(k)?+v:v);await api('/api/settings',{method:'POST',body:JSON.stringify(o)});state.settings=o;await i18n(o.language);schedule()};let full=document.createElement('button');full.textContent='JSON/CSV/XLSX';full.onclick=async()=>alert(JSON.stringify(await api('/api/export-full',{method:'POST'}),null,2));$('#export').before(full);init();
